
export const equipeData = [

  { id: '1', nome: 'Fabrine Macedo', foto: "/equipe/fabrine_macedo.webp", especialidade: "Nanopigmentação e Despigmentação a Laser", procedimentos: [{ nome: 'Design de Sobrancelhas', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }, { nome: 'Depilação Linha', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }, { nome: 'Avaliação Fabrine', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }, { nome: 'Micropigmentação Allure Brows', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }] },

  { id: '2', nome: 'Amanda Dantas', foto: "/equipe/amanda_dantas.webp", especialidade: "Podologia", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }] },
  { id: '3', nome: 'Tifanny Santana', foto: "/equipe/tifanny_santana.webp", especialidade: "Atendimento", procedimentos: [] },
  { id: '4', nome: 'Grascielly Medeiros', foto: "/equipe/grascielly.webp", especialidade: "Harmonização Facial", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }] },

  { id: '6', nome: 'Jessica Galera', foto: "/equipe/jessica.webp", especialidade: "Estética", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }] },
  { id: '7', nome: 'Katia Maya', foto: "/equipe/katia_maya.webp", especialidade: "Extensão de Cílios", procedimentos: [{ nome: 'Volume Full', description: 'Estamos atualizando os textos, entre em contato no whatsApp e veja o nosso catalogo:', fotos: [] }] },
]