
export const equipeData = [

  { id: '1', nome: 'Fabrine Macedo', foto: "/equipe/fabrine.webp", especialidade: "Nanopigmentação", procedimentos: [{ nome: 'Design de Sobrancelhas', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Depilação Linha', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Avaliação Fabrine', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Micropigmentação Allure Brows', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }] },

  { id: '2', nome: 'Amanda Dantas', foto: "/equipe/amanda.webp", especialidade: "Podologia", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }] },

  { id: '3', nome: 'Juliana Marchezetti', foto: "/equipe/juliana.webp", especialidade: "Despigmentação à Laser", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }] },

  { id: '4', nome: 'Grascielly Medeiros', foto: "/equipe/grascielly.webp", especialidade: "Harmonização Facial", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }] },

  { id: '5', nome: 'Karen Dantas', foto: "/equipe/karen.webp", especialidade: "Extensão de Cílios", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }] },

  { id: '6', nome: 'Jessica Galera', foto: "/equipe/jessica.webp", especialidade: "Estética", procedimentos: [{ nome: 'Design Estratégico', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }, { nome: 'Brows Lamination', description: 'Estamos atualizando os textos aguarde, por favor entre em contato no whatsApp e veja nosso catalogo:', fotos: [] }] },
]